name: petcom
description: E-commerce for buying and selling pets and pet products.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  uuid: ^3.0.6
  http: ^0.13.4
  khalti_flutter: ^2.0.2
  image_picker: ^0.8.5
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.12
  firebase_messaging: ^11.3.0
  flutter_otp_text_field: ^1.0.1
  onesignal_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menus/
    - assets/images/doctors/
    - assets/images/register/
    - assets/google_fonts/
